### ISSUE TITLE
No error feedback when trying to add an account without role

### ISSUE THREAD

**Issue by tobias-wiese** [upb-uc4/ui-web#412]

**Comment by bastihav** [comment]
will probably be fixed with new user endpoint merge

**Comment by tobias-wiese** [comment]
still present. Submitting an account with just the username set causes a type error
